
import googleMapsPolyline
from geojson import LineString
import pyperclip

c1 = "wb{rGyiza@~@[fC}@`@MdA_@n@QnAa@NGLCRGjAa@LE@?JEbA]\\UV[p@{@V_@HMn@}@HOp@eAJQRJL@ZCLEFCDCJCJEBAHE@?`DmAJEDALEZMdCcA\\Mf@WVKRKDAr@WfAc@PGp@WDAJELELGj@Ul@WZG`@QDECWWiDYiDAKCWOmBAOAGAMEa@McBGm@Eq@CWAIAMCg@EWC_@E]KwACQC[C[ASCYAGGy@AIAKASCWGm@AQ?AEc@RUX]nAuA|BgCHKRSBEv@_ABCFIDGDEFKHIDE^c@FIf@i@@ATYNOLODEhAsAbAeAJMJORS@AJOTW@AJKLQFE`@c@DGHIPUHIBCHI^e@HIBCBEDEHIFIzBiCFWF]n@iEZaCXoB@KBKDY?CBM@KDY?Q?G@YAMCMGUGUACI[s@}BEMGUIWeBcGCMEKGQIYmAcEqAqEGUEMI[EKi@kBCGGQoD_M[eAy@iCWk@a@y@a@s@wAgCgAsBS_@mBgDoBmD_@_AyCeFk@k@mTq]}@yAaA{AIMaEwGeC}DsBoDyB_De@{@g@_Ae@oA]iAQi@EMKYKOGIKGIEICUGYOWOYa@_CiD]g@eCmDEGMSOSQWGIMSg@w@??y@mAk@{@CEa@m@uA{Be@aACGKUU_@k@y@MSEIEGEGGK]i@KMY]qGsKk@wAQYIKAEKQCIAKBQDGJKVM\\GxBUv@]j@e@f@}@ReABaBI_AU{BMkAO_A?ACOAMESAKKa@IUcBwDWk@?CS[WY]S]Mu@I_@Ca@A_@GUGQKUMEGQMKOQWISIQK[Mc@GYAICKCOAC?EQcAe@oCWqAGy@Ak@?_@@Q?UDkA?M@]@[?AAQ?MA[AWAI]kDEw@ASAs@EsA?KAg@Ca@Es@M}@Ky@u@wFOgA[gCCMAG?Gk@cEScBIYMS_@g@_@YQUKc@Ge@CMAKE[[mBKy@WoH?_@@i@HaB?O@ADy@BIHq@Ba@@QB[?QF?HEFK@I?A?KAGCIGGGCE@AIAWAqHEi@q@cKC_@k@qIW@CB_Az@E@KHk@T[L"


c1Coords = googleMapsPolyline.decode(c1)
pyperclip.copy(LineString(c1Coords))
print(LineString(c1Coords))